### ISSUE TITLE
does not work on pi2

### ISSUE THREAD

**Issue by rajbadri** [tdicola/pi-facerec-box#2]
hi
i have been using this on a pi b+ but on a pi2 i get this error

Traceback (most recent call last):
  File "capture-positives.py", line 14, in <module>
    import hardware
  File "/home/pi/pi-facerec-box-master/hardware.py", line 8, in <module>
    import RPIO
  File "/usr/local/lib/python2.7/dist-packages/RPIO/**init**.py", line 115, in <module>
    import RPIO._GPIO as _GPIO
SystemError: This module can only be run on a Raspberry Pi!

i updated with a  a fresh copy of the Adafruit_Python_GPIO module:

still the same error comes

**Comment by tdicola** [comment]
Oh make sure to grab the latest (02-16-2015) image of Raspbian and start from there, or check out this post to install the latest RPi.GPIO library: https://blog.adafruit.com/2015/02/05/how-to-fix-error-loading-rpi-gpio-python-library-on-your-brand-new-raspberry-pi-2/  The version of that library originally shipped with the Pi 2 unfortunately had an issue and fails with that error.  However you can now just pip install an updated version and it should resolve the issue.
